baseURL = "https://dcb9.github.io/"
languageCode = "en-us"
title = "Du, Chengbin's Blog"
theme = "ink"
paginate = 20

copyright = "© Copyright Du, Chengbin"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""
disqusShortname = ""

[params]
	subtitle = "Software engineer"

	# Optional 64x64 avatar image.
	avatar = ""

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	featherIconsCDN = true

	mode = "light" # "dark" or "auto"
	customCSS = "css/katex.min.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	customJS = ["js/katex.min.js", "js/auto-render.min.js",  "js/custom.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/dcb9"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/robertduu"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
